### ISSUE TITLE
Date data type issue

### ISSUE THREAD

**Issue by siddhanathnagane** [codingchili/excelastic#11]
I am creating columns with data in excel and importing excel file to elastic search, but mapping have been created with the properties with two datatypes only.(number, string). e.g my excel-sheet contains date column but after importing to elastic search it is converting to number format.

**Comment by codingchili** [comment]
Which date format is used? If the format is not picked up by ElasticSearch automatically a mapping needs to be created for the index. Looking into it.

**Comment by codingchili** [comment]
Confirmed that there is an issue with dates, looking into it.

**Comment by codingchili** [comment]
http://joelabrahamsson.com/dynamic-mappings-and-dates-in-elasticsearch/

**Comment by codingchili** [comment]
The issue stemmed from apache poi detecting Date cells as numeric. These cells are now checked for dates using DateUtil and then converted to iso 8601 dates if applicable, using Instant::toString.

Fix not pushed yet, part of 1.2 release.
