### ISSUE TITLE
add support for es 5.4

### ISSUE THREAD

**Issue by codingchili** [codingchili/excelastic#17]

**Comment by codingchili** [comment]
Indexes without errors, check if data is intact.

**Comment by RedCloudDC** [comment]
for reals? works w 5.4.x?

**Comment by codingchili** [comment]
Tested working fine with a simple xlsx file on 5.4.2. Needs more testing and some small features before releasing.

**Comment by codingchili** [comment]
closing this, works on snapshot-1.2.
