### ISSUE TITLE
Any Limit on data file?

### ISSUE THREAD

**Issue by prateeknepaliya09** [codingchili/excelastic#2]
I am trying to upload a 16MB file (excel), it is getting uploaded but it doesn't Show up in my elasticsearch cluster.

**Comment by codingchili** [comment]
Noticed the same in another project when sending large log events to elasticsearch. Try running a more recent version of ES, at least alpha5.

**Comment by prateeknepaliya09** [comment]
Worked. Thanks.

**Comment by codingchili** [comment]
Updated README file to list the released version of ElasticSearch 5.0.0 as a requirement.
