### ISSUE TITLE
install help?

### ISSUE THREAD

**Issue by RedCloudDC** [codingchili/excelastic#32]
Robin (sorry if this is basic question)...ELK is running and ready to go.

installing your app - when I unzip there is no jar file called excelastic-1.2.0 to run

java -jar excelastic-1.2.0.jar

can you update readme with install instructions?

**Comment by codingchili** [comment]
Hello,

The jar-file is not packaged within a zip, it seems you might have downloaded the sources only. The .jar file and the configuration is available on the releases page. If you have maven installed you could build the jar from the sources using
`mvn package`

Attempted to clarify the installation steps in https://github.com/codingchili/parser-excel-elasticsearch/commit/511bbe2c9f38c0384965d97b15e5d204cabc1054
