### ISSUE TITLE
data lost

### ISSUE THREAD

**Issue by DavidMaer** [codingchili/excelastic#33]
I uploaded an excel with more than 60,000 data, but only more than 10,000 data in Elasticsearch after uploading.

**Comment by codingchili** [comment]
Thanks for submitting an issue. 

it is very likely that this issue is caused by the lack of back-pressure. When submitting batches for indexing the application should wait until the previously submitted batches are completed. Looking into this.

**Comment by codingchili** [comment]
fixed in version 1.2.1, batches are now executed in order and not concurrently.
