### ISSUE TITLE
How to upload with security enabled in Elastic?

### ISSUE THREAD

**Issue by ponten68** [codingchili/excelastic#39]
How do I pass user credentials, either from command prompt or user interface when uploading an Excel file?
Now I just receive status 401, unauthorized of course, and [ES connected=false]
Running 1.2.2b
Elasticsearch 5.5.0

Security enabled by default with X-Pack, only Basic license runs without, but I need extra features on my system....
Not possible to disable Security in Elastic (not even temporarily). 
Would you consider adding input of credentials?

Kind regards

**Comment by codingchili** [comment]
Hello! 

I have looked into adding this feature, looks like a small thing to add. I read about using basic http authentication, is this what you want to use? 

Regards

**Comment by ponten68** [comment]
Hi,
yes I believe that would do fine. Suppose that's how for example Logstash does it as well. 

Thx for your responsiveness

**Comment by codingchili** [comment]
Have not forgotten about this, have to postpone the fix for later. A critical bug was fixed instead. Expect to look into this within 2 weeks.

**Comment by codingchili** [comment]
Fixed in latest release: https://github.com/codingchili/parser-excel-elasticsearch/releases/tag/1.2.4
