### ISSUE TITLE
 result [406] Not Acceptable into "Index"

### ISSUE THREAD

**Issue by JoelJoy58** [codingchili/excelastic#47]
i am getting this error. while trying to upload the data in both the web as well as command way. any suggestions?
java -Xmx1g -jar excelastic-1.2.4.jar "D:\Shared Folder\Book1.xlsx" UseCase2

**Comment by JoelJoy58** [comment]
even if i execute the jar. its displaying Success.


but the index was not created in kibana

**Comment by codingchili** [comment]
Hello

Could you attach Book1.xlsx to this issue?

Not sure what "not acceptable" means,  maybe inconsistent data types?

**Comment by codingchili** [comment]
Which version of elasticsearch are you running?

Which version of java?

**Comment by JoelJoy58** [comment]
im running ELasticsearch 6
dis is a sample excel file


usecase | Project | Target FTE | Estimate date
-- | -- | -- | --
1 | asd | 1.14 | 18-Jan
2 | bud | 2 | 17-Dec
3 | shock | 0.4 | 1-Apr


once i done uploading i getting success message but the data is not uploaded or index is not created in kibana

**Comment by codingchili** [comment]
Have not tested v6,  not sure its compatible since its a new major. Tested with 5.6.2. 

Possible it does not appear as the sample file is missing recognized dates? Check compatible data formats. Will look into adding v6 support soon.

**Comment by JoelJoy58** [comment]
ok i will check and get back to you.

**Comment by JoelJoy58** [comment]
Its working fine with 5.6.2. Thanks @codingchili .
please do let me know once you made an update for the version 6.
Thanks Again.

**Comment by codingchili** [comment]
Thanks for the update will do, created issue #48 for this. 
Closing this issue for now.
