### ISSUE TITLE
Verify support for ElasticSearch v6

### ISSUE THREAD

**Issue by codingchili** [codingchili/excelastic#48]

**Comment by codingchili** [comment]
Strict content type, need to add application/json.

**Comment by JoelJoy58** [comment]
need to add application/json -- means what. which json need to added

**Comment by codingchili** [comment]
The http header "Content-Type" needs to be set for all requests to elasticsearch 6. With the value of "application/json". This is a new requirement in v6 and when missing, elasticsearch returns 406. I will update the code to add this header.

See https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

**Comment by codingchili** [comment]
@JoelJoy58 @S-J-D-13 

Added support for ES 6.1 in version 1.2.5, now available here https://github.com/codingchili/parser-excel-elasticsearch/releases/tag/1.2.5
