### ISSUE TITLE
issue in uploading the excel

### ISSUE THREAD

**Issue by JoelJoy58** [codingchili/excelastic#49]
i am trying to upload a xlsx sheet with some 60,000 rows,. i am unable to upload the data.
getting the below error

java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by codingchili** [comment]
Hello

Currently the whole excel file is parsed in memory before the import starts. There is a proåosal to reduce memory usage #44 

Until fixed you could try increasing heap space by passing -Xmx4G after -jar when starting.

Make sure to use a 64bit jvm.

**Comment by JoelJoy58** [comment]
That works..
Thanks @codingchili

**Comment by codingchili** [comment]
Closing for now, to be fixed in #44
