### ISSUE TITLE
Error using web client

### ISSUE THREAD

**Issue by RedCloudDC** [codingchili/excelastic#50]
![screenshot 2017-12-06 19 07 54](https://user-images.githubusercontent.com/4070409/33694610-1faa38fe-dac7-11e7-9e67-d7d7706d2819.png)

**Comment by codingchili** [comment]
Hello,

Which version of excelastic are you using? Could you provide a file that fails to import? 

There have been some issues with the counting of columns. There are multiple ways to determine the column count and each solution fails in different special cases. It would be nice to fix this for good.

Thanks for submitting an issue.

**Comment by codingchili** [comment]
Any updates on this? @RedCloudDC

**Comment by codingchili** [comment]
No feedback, closing,
