### ISSUE TITLE
Cannot use excelastic when x-pack installed

### ISSUE THREAD

**Issue by natsirasrafi** [codingchili/excelastic#52]
Cannot use excelastic when x-pack installed the error message is cannot connected

**Comment by codingchili** [comment]
Hello,

would it be possible to provide some more information? 

- which x-pack components are you using, is security enabled? 
- how does you excelastic configuration look like? did you enable http basic auth?
- is the elasticsearch server running on https? 

Thanks for submitting an issue, Regards.

**Comment by codingchili** [comment]
As noted in another issue TLS was not actually enabled for the ES client. The readme has been updated, see elastic_tls for connecting to secured servers.
