### ISSUE TITLE
automatic import in elastic 

### ISSUE THREAD

**Issue by alexismarin** [codingchili/excelastic#53]
Hello,
Your plugin is very very nice tanks you a lot :) .
I would want to import automatically xslx in elastic with your plugin and what that is possible? Without passing by the interface but on-line of commanddirectly on the server is possible ?

thanks you for you reply.

Alexis Marin

**Comment by codingchili** [comment]
Hello hello,

This feature is not supported right now. Maybe it could be done in a script, or added as a feature.

Could you elaborate on the use case? Would importing new/modified files from a specific folder on disk work? Could be combined with an ftp server and be quite useful.

Thanks for submitting an issue,

Regards

**Comment by codingchili** [comment]
No update, closing.
