### ISSUE TITLE
Error - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by syiand** [codingchili/excelastic#54]
Hello,

thank you for creating the plugin :) 

Elasticsearch Version: 6.1.1. | Excelastic Version: 1.2.5

I tried to parse a xlsx file and I got this error: 
```
com.codingchili.Model.ParserException: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.codingchili.Model.FileParser.<init>(FileParser.java:60)
	at com.codingchili.Controller.Website.lambda$parse$12(Website.java:175)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:278)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.codingchili.Model.FileParser.getRow(FileParser.java:216)
	at com.codingchili.Model.FileParser.readRows(FileParser.java:120)
	at com.codingchili.Model.FileParser.<init>(FileParser.java:54)
	... 5 more
```

**Comment by codingchili** [comment]
Hello
 This is a common issue that is related to the cell format/layout of your excel file. Would it be possible for you to provide a file that yields this error?

Thanks for submitting an issue

**Comment by syiand** [comment]
Hello,

thank you for the prompt response! I can't really share the file, because it contains sensitive information. If that helps, the file has 8 columns and 650 rows. It's just a normal file with a lot of text and numbers. Are there any possible triggers that cause that kind of issue? Or is there any specific format appropriate? For example the numbers should be 1,234 instead of 1.234 or anything like this?

Thank you in advance

**Comment by codingchili** [comment]
Hello, 

The issue has to do with detecting the number of columns. Make sure there are no rows with more columns than in the title row. Sometimes there can be empty cells within a sheet that gets detected as having content.

Its a bit strange to see 1 as being out of bounds, this would indicate that you only have 1 column in your title row, or has set the title-row to an empty row. 

Make sure your layout is as follows
1|  Id | Name   | Year
2|   1 | Testing | 2018 
3|   2 | Testing | 2019 
....
In this example the title row should be set to 1 when importing. Rows 2..N should not have more cells than 3. 

A possible improvement would be to just skip importing cells with a higher column index than the number of titles. Dots or decimals does not matter as long as the cell is formatted as a numeric value and matches your current locale settings.

**Comment by syiand** [comment]
Hey,
Your response helped me find the problem. The file had an extra sheet which I didn't notice. It was indeed exactly as you mentioned.
I am closing the issue. Thanks for the help and for the really useful plugin :)
