### ISSUE TITLE
Connecting to elasticsearch server running on https

### ISSUE THREAD

**Issue by Trouble123** [codingchili/excelastic#55]
Hi
Is there a setting that you need to enable so that you can connect to a https enabled ES cluster?
I am running ES 6.2.1.

Thanks

**Comment by codingchili** [comment]
Hello,

Seems like this is currently not supported. I will add support for enabling TLS in the configuration/commandline options.

Thanks for submitting an issue!

**Comment by codingchili** [comment]
Hello, 

Added a configuration option to enable TLS when communication with elasticsearch.

See the updated readme regarding "elastic_tls".

Let me know if you have any more issues.

**Comment by Trouble123** [comment]
Thanks, looks to be working great.
