### ISSUE TITLE
Problem with tls elasticsearch

### ISSUE THREAD

**Issue by Beast12** [codingchili/excelastic#59]
Hi,
When I try to connect to my secure cluster I get following error:
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem

My configuration.json file:
{
  "web_port": 0,
  "elastic_port": 9200,
  "elastic_host": "esclient01prod",
  "elastic_tls": true,
  "authentication": true,
  "basic": "elastic:*******"
}

**Comment by codingchili** [comment]
Hello,

Is the server using a certificate that is signed by a trusted CA? 

If the server certificate is self-signed it needs to be trusted by the JVM.

Regards,
