### ISSUE TITLE
CSV upload

### ISSUE THREAD

**Issue by sathyajackson** [codingchili/excelastic#61]
Hi,

Need you help i have a csv file which is close to 26 G and its not possible for me to open and convert the file to xls or xxls. I need your help in code accepting the csv format.

**Comment by codingchili** [comment]
Hello Sathya, 

Let me see if I can work the magic. This should be an easy fix.

Regards, 
Robin

**Comment by sathyajackson** [comment]
Thank you, Robin 👍 . I love to use your tool and expecting  the new release with enhancement as early as possible 🥇

**Comment by sathyajackson** [comment]
HI Any update ?

**Comment by codingchili** [comment]
Hello I started looking into it. Am not currently able to continue until end of week. :) I will let you know when there's further progress.

**Comment by sathyajackson** [comment]
Thank you 👍

**Comment by sathyajackson** [comment]
HI,

I just saw your post on limit exceeded #62, good to know that we are expecting a change. Waiting for the update so that i can use it o production :)

**Comment by codingchili** [comment]
Hi sorry, have not found the time to work on this yet. Probably 1-2 more weeks before it's fixed.

**Comment by sathyajackson** [comment]
Any update ?

**Comment by codingchili** [comment]
Hello,

There is a new release, 1.3.0 with support for CSV files.
I have not done any benchmarking so I don't know how it performs.

It should be much better than excel at least.

https://github.com/codingchili/parser-excel-elasticsearch/releases

Please open a new issue if you encounter any issues.
