### ISSUE TITLE
Set default index

### ISSUE THREAD

**Issue by kobybr** [codingchili/excelastic#67]
Would be nice to be able to set a custom default index instead of the Month-Year and/or be able to disable end-user from modify said default.

**Comment by codingchili** [comment]
Hello,

Yep, let's do it!
Very simple, should be in the next release.

Thanks for submitting an issue.

**Comment by codingchili** [comment]
Fixed in 1.3.3 - new configuration option in application.json, "default_index". if unset will default to month-year.

**Comment by kobybr** [comment]
Can we have an option to also disable the user from changing the index name?   If I set the index name, I would want to prevent the end-user from renaming.  Otherwise, I can end up with a bunch of random indexes in elasticsearch

**Comment by codingchili** [comment]
Yes, of course!

Opened #72
