### ISSUE TITLE
Question about file inputs

### ISSUE THREAD

**Issue by DefensiveThinking** [codingchili/excelastic#73]
First I want to say thank you for saving me countless hours. 
Second I was wondering in the next release if you could put in upload from directory instead of files? 
Not sure how hard that would be but it would be very helpful

**Comment by codingchili** [comment]
Hello,

Yes - this is easier than supporting multiple worksheets and will be implemented first.

I'm spending time on some other projects right now - I can't give you an estimate when it will be done. It's on the roadmap now :)

BR

**Comment by codingchili** [comment]
Closing this for now, I don't have the time to fix this. 

If this is required I would recommend writing a script or submitting a PR.
