### ISSUE TITLE
Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by kripskroll** [codingchili/excelastic#76]
Hi,

Launching
#java -Xm2g -jar excelastic-1.3.4.jar 
I have this errot output : 
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Here is my system
Debian 9.5 CLI only
Java 1.8.0-192

Do I need to have an X Server / Windows Manager ?

Thanks

**Comment by codingchili** [comment]
Hello,

No, how much memory do you have available? 

Try removing -Xmx2g or set it to 1g.

- R
