### ISSUE TITLE
Create a new main-class

### ISSUE THREAD

**Issue by codingchili** [codingchili/excelastic#8]
Users should not have to enter the 'run Launcher' arguments.

**Comment by RedCloudDC** [comment]
I have es running on my laptop with tons of excel files. the readme needs more details what do I enter for <filename.jar>? There are no archives in the app and es has hundreds so can you help?

**Comment by codingchili** [comment]
The jar can be downloaded from here.
https://github.com/codingchili/parser-excel-elasticsearch/releases

excelastic is the name of the jar, the configuration.json file needs to be present in the same directory. 
Updated the readme to include the real filename.

**Comment by codingchili** [comment]
Fixed on snapshot.
