### ISSUE TITLE
Error web client important number of row

### ISSUE THREAD

**Issue by Hiruxou** [codingchili/excelastic#82]
Hi !

I'm trying to import a large file csv with web client but i have an error : 
![excelastic](https://user-images.githubusercontent.com/14022367/55788205-2ef80800-5ab8-11e9-82e6-dd62c23c0a5f.PNG)

My CSV have 10 000 000 row, 820 000 Ko.
My title as in row 0, my line finish with "CR LF", i have no blank line at the end of my file.
i'm using the latest version of excelastic.
Can you help me ?

**Comment by codingchili** [comment]
Hello!

How many columns are there in the csv file on the first row? The application detects 12, with an anomaly on line 5403058 where it finds only 11 columns. what does this line look like? 

BR

**Comment by Hiruxou** [comment]
Hi !
thank you for your fast reply !

I have 12 columns and the line 5403058 is : 
![linedefault](https://user-images.githubusercontent.com/14022367/55862241-57473b80-5b78-11e9-9f78-b276b32c682c.PNG)
_Line in the middle_

Sorry for the censorship but i have no choice.

-----------------------------------------EDIT-----------------------------------------
new information : 
![image](https://user-images.githubusercontent.com/14022367/55870356-ae550c80-5b88-11e9-8e92-b7e3e1a5a60b.png)

I think it's block after line 5403058 because thread is blocked and he consider he can not found the 12 element of my line.

-----------------------------------------EDIT-----------------------------------------
Also with little csv (42 line) another error : 
![failed](https://user-images.githubusercontent.com/14022367/55875234-d77b9a00-5b94-11e9-95f6-542ecd761c80.PNG)

`"CODE_X","CODE_X","CODE_X","CODE_X","CODE_X","CODE_X","CODE_X","CODE_X","CODE_HORAIRE","DATE_X","DATE_X","NB_X","SURFACE_X","ALTX","X","Y","FLAG_X","LIB_X","LIB_X","DESC_X"`

`N4122,ST,,,,[INT],HG,17,1,1987-09-09 00:00:00,,1,,2230,384455,[INT],1,ëlou,"ëlou (Gave d Azun, 2260m) N4122",`
_I have to replace some data in row with X._

But i have 20 column in my tittle ..

**Comment by Hiruxou** [comment]
Up ! 

new information : 
![image](https://user-images.githubusercontent.com/14022367/55870356-ae550c80-5b88-11e9-8e92-b7e3e1a5a60b.png)

I think it's block after line 5403058 because thread is blocked and he consider he can not found the 12 element of my line.

**Comment by codingchili** [comment]
Thanks for the update!

Seems to be an issue with the headers for the small CSV.

Any special characters in there? Or commas within quotes?

**Comment by Hiruxou** [comment]
For the large file (10 000 000 rows) format it's ok, i think it's the thread who can not support the number of row (may be?).

For the little CSV but i think i have some trouble with commas and/or quotes. I will check now !

**Comment by codingchili** [comment]
Hi again,

The blocked thread warning is expected for large files, it just means that the thread is busy processing. 10M rows will take a while to complete, do you see any status updates logged?

**Comment by codingchili** [comment]
No you won't see any status updates yet, because it's doing the initial parse of the file to ensure it's able to parse the whole file.

**Comment by Hiruxou** [comment]
Hi !

So, for little CSV it's my bad, the export of database was corrupted now it's ok thank you !

I'm going to try series test, i'll keep you informed.

**Comment by Hiruxou** [comment]
![image](https://user-images.githubusercontent.com/14022367/55945972-1882b580-5c4c-11e9-8423-046e58df2bf1.png)

![image](https://user-images.githubusercontent.com/14022367/55946046-3bad6500-5c4c-11e9-8149-2afc1a2241d0.png)

What am I doing wrong? You have an idea ?

**Comment by codingchili** [comment]
it looks like there's not enough columns in the data rows to match the header.

not sure why it errors at row 3 with 0 values though, try to ensure the data columns match the header count in the shown lines.

**Comment by codingchili** [comment]
closing, please reopen if this is still an issue.
