### ISSUE TITLE
No visualization available 

### ISSUE THREAD

**Issue by amit4aws** [codingchili/excelastic#84]
Everything works fine but the dashboard does not populate and does not show the visual chats using the samle xls. Am i missing something

**Comment by codingchili** [comment]
Hello,

Which sample xml are you using?

Try searching on the discover workspace to make sure there is some data. I usually forget to set a timespan on my dashoard/visualizations and get zero hits. Make sure there is a timestamp field in the index configuration.

**Comment by codingchili** [comment]
closed due to inactivity, please reopen if required.
