### ISSUE TITLE
mapping of "true" and "false" values in xlsx to "type": "boolean" in Elastic

### ISSUE THREAD

**Issue by rsajpon** [codingchili/excelastic#88]
excelasitc: 1.3.7
elasticsearch 7.2

Love code, have used it a number of times.

Now got into trouble when uploading an xlsx file with "true" and "false" values.
How would I need to format the xlsx in order to have those values properly translated into "type: "boolean" in Elastic?

See below, import from csv works fine.
The xlsx source file generating xlsxbool index has the column cells formatted as "General" in Excel.
The xlsx source file generating xlsxbool2 index has the same column cells formatted as "Text".

![csvbool_source](https://user-images.githubusercontent.com/61098462/74597057-b0191780-5058-11ea-81d7-90c1f47ddd59.JPG)
![xlsxbool_source](https://user-images.githubusercontent.com/61098462/74597061-b4ddcb80-5058-11ea-8ba5-a33b0b2a029b.JPG)

```

get csvbool

{
  "csvbool" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "Question 1" : {
          "type" : "boolean"
        },
        "Question 2" : {
          "type" : "boolean"
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1581809770044",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "SGC9yDIOSZSzV2p_BBRTPQ",
        "version" : {
          "created" : "7020199"
        },
        "provided_name" : "csvbool"
      }
    }
  }
}


get xlsxbool

{
  "xlsxbool" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1581809945085",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "cHHhTc_aRMa5sggOnfhffw",
        "version" : {
          "created" : "7020199"
        },
        "provided_name" : "xlsxbool"
      }
    }
  }
}

{
  "xlsxbool2" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "Question 1" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "Question 2" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1581810257863",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "RiI3Q04XRyq22MyzFfoucA",
        "version" : {
          "created" : "7020199"
        },
        "provided_name" : "xlsxbool2"
      }
    }
  }
}

```
So Elasticsearch is not creating any mapping at all in the first xlsx case.
elastic log:
> [2020-02-16T01:16:07,491][INFO ][o.e.c.m.MetaDataCreateIndexService] [node1] [xlsxbool] creating index, cause [auto(bulk api)], templates [], shards [1]/[1], mappings []
> [2020-02-16T01:16:07,594][INFO ][o.e.c.m.MetaDataMappingService] [node1] [xlsxbool/O3Kd1CzFQtOXNa3_7c4tEw] create_mapping [default]
> 

In the second it creates mapping as "text", not "boolean".
elastic log:

> [2020-02-16T01:19:05,221][INFO ][o.e.c.m.MetaDataCreateIndexService] [node1] [xlsxbool2] creating index, cause [auto(bulk api)], templates [], shards [1]/[1], mappings []
> [2020-02-16T01:19:05,317][INFO ][o.e.c.m.MetaDataMappingService] [node1] [xlsxbool2/2kiyPZG4SlW1qfK_r2R8nw] create_mapping [default]

Am I just missing how to prepare the xlsx file properly or is there a bug here?

Regard,
Johan

**Comment by rsajpon** [comment]
Was able to upload the xlsx file now with cell format "text", but **only if manually creating the index and mapping beforehand**:

```
PUT xlsxbool2?include_type_name=true
{
  "mappings": {
    "_doc": {
    "properties": {
      "Question 1": {
        "type": "boolean"
      },
      "Question 2": {
        "type": "boolean"
      }
    }
  }
  }
}

get xlsxbool2

{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "xlsxbool2",
        "_type" : "_doc",
        "_id" : "1iCVS3AB_SHNfswVnXsg",
        "_score" : 1.0,
        "_source" : {
          "Question 1" : "true",
          "Question 2" : "true"
        }
      },
      {
        "_index" : "xlsxbool2",
        "_type" : "_doc",
        "_id" : "1yCVS3AB_SHNfswVnXsg",
        "_score" : 1.0,
        "_source" : {
          "Question 1" : "false",
          "Question 2" : "true"
        }
      }
    ]
  }
}
```

**Comment by codingchili** [comment]
Hello, 

Thanks for reporting an issue! (and thank you for your patience)

Excelastic will never create a mapping, this has to be done manually if required - it uses the default mapping unless a template mapping name is given when uploading.

The problem here is that the Excel parser does not attempt to parse types and just uses the cell type (string/numeric), while the CSV parser does. This is an inconsistency that needs to be fixed.

**Comment by codingchili** [comment]
1.3.8 has been released with improvements to how types are inferred.

The following types are detected from plain strings, csv/excel.
"1.314" -> Number/Float
"3000" -> Long
"true"/"false" -> Boolean

Adds support for the BOOLEAN cell type in Excel files, string based inference will not be applied for BOOLEAN/NUMERIC cells.

Everything else is a string, dates are not parsed unless its a DATE cell.
